kind: Service
apiVersion: v1
metadata:
  name: prometheus-server-service
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090