apiVersion: v1
kind: ReplicationController
metadata:
  name: java-pet
spec:
  replicas: 1
  selector:
    app: java-pet
  template:
    metadata:
      name: java-pet
      labels:
        app: java-pet
    spec:
      containers:
      - name: java-pet
        image: java-pet2
        imagePullPolicy: Never
        ports:
        - containerPort: 6390
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
        volumeMounts:
        - mountPath: /java-pet-master-data
          name: data
        - mountPath: /java-pet-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: self-java-pet